services:
  nginx: 
    build: ./nginx
    container_name: nginx
    ports: 
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  auth:
    build: ./auth
    container_name: auth
    # ports:
    #   - 8080:8080
    volumes:
      - ./auth:/app
  chat:
    build: ./chat
    container_name: chat
    ports:
      - 8080:8080
    volumes:
      - ./chat:/app
    
  

  online_users:
    build: ./online_users
    container_name: online_users
    ports: 
      - 6379:6379